[package]
name = "rustlogistics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
# [workspace]
# resolver = "2"

# members = [
#  "api",
#   "web"
# ]


[dependencies]
time = { version = "0.3.28", features = ["serde", "parsing", "formatting", "local-offset"] }
md5 = "0.7.0"
passwords = "3.1.16"
serde = { version = "1.0.192", features = ["derive"] }
serde_json = "1.0.94"
sqlx = { version = "0.7.2", features = ["macros", "runtime-tokio-rustls", "postgres", "time"] }
uuid = { version = "1.3.0", features = ["v4", "v7", "serde"] }
serde_default = "0.2.0"
